-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-13 15:07:06 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE Dostawy 
    (
     id INTEGER NOT NULL , 
     nazwa VARCHAR (100) NOT NULL , 
     firma VARCHAR (150) NOT NULL , 
     cena DECIMAL (6,2) NOT NULL 
    )
GO

ALTER TABLE Dostawy ADD CONSTRAINT Dostawy_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Kategorie 
    (
     id INTEGER NOT NULL , 
     opis VARCHAR (100) NOT NULL 
    )
GO

ALTER TABLE Kategorie ADD CONSTRAINT Kategorie_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Licytacje 
    (
     id INTEGER NOT NULL , 
     data_rozpoczêcia DATE NOT NULL , 
     Statusy_id INTEGER NOT NULL , 
     data_zakoñczenia DATE , 
     Przedmioty_numer INTEGER NOT NULL , 
     zwyciêzca VARCHAR (50) NOT NULL 
    )
GO

ALTER TABLE Licytacje ADD CONSTRAINT Licytacje_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Oferty 
    (
     id INTEGER NOT NULL , 
     data DATE NOT NULL , 
     godzina TIME NOT NULL , 
     kwota DECIMAL (6,2) NOT NULL , 
     U¿ytkownicy_login VARCHAR (50) NOT NULL , 
     Licytacje_id INTEGER NOT NULL 
    )
GO

ALTER TABLE Oferty ADD CONSTRAINT Oferty_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Opcje_Dostawy 
    (
     Przedmioty_numer INTEGER NOT NULL , 
     Dostawy_id INTEGER NOT NULL 
    )
GO

ALTER TABLE Opcje_Dostawy ADD CONSTRAINT Opcje_Dostawy_PK PRIMARY KEY CLUSTERED (Przedmioty_numer, Dostawy_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Przedmioty 
    (
     numer INTEGER NOT NULL , 
     nazwa VARCHAR (150) NOT NULL , 
     kategoria VARCHAR (100) NOT NULL , 
     cena_wyjœciowa DECIMAL (6,2) NOT NULL , 
     opis TEXT , 
     cena_zakupu DECIMAL (6,2) , 
     U¿ytkownicy_login VARCHAR (50) NOT NULL , 
     Kategorie_id INTEGER NOT NULL 
    )
GO

ALTER TABLE Przedmioty ADD CONSTRAINT Przedmioty_PK PRIMARY KEY CLUSTERED (numer)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Statusy 
    (
     id INTEGER NOT NULL , 
     opis VARCHAR (50) NOT NULL 
    )
GO

ALTER TABLE Statusy ADD CONSTRAINT Statusy_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE U¿ytkownicy 
    (
     login VARCHAR (50) NOT NULL , 
     imiê VARCHAR (50) NOT NULL , 
     nazwisko VARCHAR (50) NOT NULL , 
     adres_zamieszkania VARCHAR (150) NOT NULL , 
     "e-mail" VARCHAR (100) NOT NULL , 
     numer_konta NUMERIC (26) , 
     adres_dostawy VARCHAR (150) , 
     telefon VARCHAR (20) 
    )
GO

ALTER TABLE U¿ytkownicy ADD CONSTRAINT U¿ytkownicy_PK PRIMARY KEY CLUSTERED (login)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Licytacje 
    ADD CONSTRAINT Licytacje_Przedmioty_FK FOREIGN KEY 
    ( 
     Przedmioty_numer
    ) 
    REFERENCES Przedmioty 
    ( 
     numer 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Licytacje 
    ADD CONSTRAINT Licytacje_Statusy_FK FOREIGN KEY 
    ( 
     Statusy_id
    ) 
    REFERENCES Statusy 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Licytacje 
    ADD CONSTRAINT Licytacje_U¿ytkownicy_FK FOREIGN KEY 
    ( 
     zwyciêzca
    ) 
    REFERENCES U¿ytkownicy 
    ( 
     login 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Oferty 
    ADD CONSTRAINT Oferty_Licytacje_FK FOREIGN KEY 
    ( 
     Licytacje_id
    ) 
    REFERENCES Licytacje 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Oferty 
    ADD CONSTRAINT Oferty_U¿ytkownicy_FK FOREIGN KEY 
    ( 
     U¿ytkownicy_login
    ) 
    REFERENCES U¿ytkownicy 
    ( 
     login 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Opcje_Dostawy 
    ADD CONSTRAINT Opcje_Dostawy_Dostawy_FK FOREIGN KEY 
    ( 
     Dostawy_id
    ) 
    REFERENCES Dostawy 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Opcje_Dostawy 
    ADD CONSTRAINT Opcje_Dostawy_Przedmioty_FK FOREIGN KEY 
    ( 
     Przedmioty_numer
    ) 
    REFERENCES Przedmioty 
    ( 
     numer 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Przedmioty 
    ADD CONSTRAINT Przedmioty_Kategorie_FK FOREIGN KEY 
    ( 
     Kategorie_id
    ) 
    REFERENCES Kategorie 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Przedmioty 
    ADD CONSTRAINT Przedmioty_U¿ytkownicy_FK FOREIGN KEY 
    ( 
     U¿ytkownicy_login
    ) 
    REFERENCES U¿ytkownicy 
    ( 
     login 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
